name: General Release
description: 'A simple action that has an option to toggle `include administrators` on branch protection, and then run semantic-release with a given release config'
inputs:
  token:
    description: 'git token to use for the run'
    required: true
  toggle-admins:
    description: 'If true, this action will disable the `include administrators` setting in branch protection for this branch, and re-enable it after release. Re-enabling is run using always()'
    required: false
    default: 'false'
  release-config:
    description: 'The release configuration to use for the release.'
    required: false
    default: '@catalystsquad/release-config-general'
  working-directory:
    description: 'Directory to run semantic-release in'
    required: false
  checkout-repo:
    description: 'Whether to checkout the repo at the beginning of the action'
    required: false
    default: 'true'
outputs:
  new-release-published:
    description: "The value of new_release_published from semantic-release"
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  new-release-version:
    description: "The value of new_release_version from semantic-release"
    value: ${{ steps.semantic-release.outputs.new_release_version }}
runs:
  using: composite
  steps:
    - name: Checkout
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
    - uses: catalystsquad/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true'
      with:
        token: ${{ inputs.token }}
        include-admins: false
    - id: semantic-release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        working_directory: ${{ inputs.working-directory }}
        extends: ${{ inputs.release-config }}
    - uses: catalystsquad/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true' && always()  # Force to always run this step to ensure "include administrators" is always turned back on
      with:
        token: ${{ inputs.token }}
        include-admins: true
